export const ScreenName = {
    AuthStack: 'AuthStack',
    LoginScreen: 'LoginScreen',
    SignupScreen: 'SignupScreen',
    GameLobbyScreen: 'GameLobbyScreen',
    CreatePassword: 'CreatePassword',
    EnterEmailScreen: 'EnterEmailScreen',
    MainScreen: 'MainScreen',
    CreateFullName: 'CreateFullName',
    CreateDateOfBirthScreen: 'CreateDateOfBirthScreen',
    CreateAddress: 'CreateAddress',
    HomeStack: 'HomeStack',
    HomeScreen: 'HomeScreen',
    MyProfileStack: 'MyProfileStack',
    RoundStack: 'RoundStack',
    SettingStack: 'SettingStack',
    BottomTabs: 'BottomTabs',
    MyProfileScreen: 'MyProfileScreen',
    RoundScreen: 'RoundScreen',
    SettingScreen: 'SettingScreen',
};
