export const string = {
  "MaterialIcons": "MaterialIcons",
  "AntDesign": "AntDesign",
  "email": "email",
  "apple1": "apple1",
  "google": "google",
  "sign_in_with_email": "Sign in with Email",
  "sign_in_with_apple": "Sign in with Apple",
  "Email": "EMAIL",
  "create_an_account": "Create an account",
  "promo_code_opt": "PROMO CODE (OPT.)",
  "enter_your_email": "Enter your email",
  "enter_your_promo_code": "Enter your promo code",
  "type_here": "Type here",
  "password": "Password",
  "enter_your_password": "Enter your password",
  "next": "Next",
  "sign_in": "Sign In",
  "go_back": "Go Back",
  "login":"LOGIN",
  "please_sign_in_to_continue": "Please sign in to continue",
  "enter_your_email": "ENTER YOUR EMAIL",
  "you_ll_use_this_to_log_into_your_account": "You’ll use this to log into your account.",
  "step_1_of_5": "STEP 1 OF 5",
  "first_name": "FIRST NAME",
  "last_name": "LAST NAME",
  "enter_your_full_name": "ENTER YOUR FULL\nNAME",
  "important": "IMPORTANT",
  "make_sure_this_info_matches_your_driver_s_license": "Make sure this info matches your\ndriver’s license",
  "enter_your_date_of_birth":"ENTER YOUR DATE\nOF BIRTH",
  "month":"MONTH",
  "day":"DAY",
  "year":"YEAR",
};
