export const string = {
  "MaterialIcons": "MaterialIcons",
  "AntDesign": "AntDesign",
  "email": "email",
  "apple1": "apple1",
  "google": "google",
  "sign_in_with_email": "Sign in with Email",
  "sign_in_with_apple": "Sign in with Apple",
  "Email": "EMAIL",
  "create_an_account": "Create an account",
  "promo_code_opt": "PROMO CODE (OPT.)",
  "enter_your_email": "Enter your email",
  "enter_your_promo_code": "Enter your promo code",
  "type_here": "Type here",
  "password": "Password",
  "enter_your_password": "Enter your password",
  "next": "Next",
  "sign_in": "Sign In",
  "go_back": "Go Back",
  "login":"LOGIN",
  "please_sign_in_to_continue": "Please sign in to continue",
  "enter_your_email": "ENTER YOUR EMAIL",
  "you_ll_use_this_to_log_into_your_account": "You’ll use this to log into your account.",
  "step_1_of_5": "STEP 1 OF 5",
  "first_name": "FIRST NAME",
  "last_name": "LAST NAME",
  "enter_your_full_name": "ENTER YOUR FULL\nNAME",
  "important": "IMPORTANT",
  "make_sure_this_info_matches_your_driver_s_license": "Make sure this info matches your\ndriver’s license",
  "enter_your_date_of_birth":"ENTER YOUR DATE\nOF BIRTH",
  "month":"MONTH",
  "day":"DAY",
  "year":"YEAR",
  "enter_your_address": "ENTER YOUR\nADDRESS",
  "address": "ADDRESS",
  "start_searching_here": "Start searching here...",
  "confirm_current_location": "Confirm current location",
  "location": "Location: ",
  "create_your_password": "CREATE YOUR PASSWORD",
  "must_contain_at_least_1_uppercase_letter":"Must contain at least 1 uppercase letter, 1 number, 1 special character.",
  "must_be_at_least_8_characters_long":"Must be at least 8 characters long.",
  "terms_of_service": "Terms of service",
  "privacy_policy": "\nPrivacy Policy",
  "by_creating_an_account_you_agree_to_Swing_Stakes": "By creating an account, you (1) agree to\nSwing Stakes ",
  "including_the_arbitration_provision_and": ",\nincluding the arbitration provision and",
  "acknowledge_that_you_have_received": " (2) acknowledge that you\nhave received and reviewed those documents, and (3) confirm that you are\nof legal age to participate in Swing\nStakes contests.",
  "change_password":"CHANGE\nPASSWORD.",
  "old_password": "OLD PASSWORD",
  "new_password": "NEW PASSWORD",
  "confirm": "Confirm",
  "cancel": "Cancel",
  "change_email": "CHANGE\nEMAIL.",
  "new_email": "NEW EMAIL",
  "enter_your_old_email": "Enter your old email",
  "enter_your_new_email": "Enter your new email",
  "your_current_email_will_be_sent" : "Your current email will be sent a confirmation of your new email change. please follow the link to confirm.",
  "change_address": "CHANGE\nADDRESS.",
  "upon_changing_your_address_you_will": "Upon changing your address you will be required to complete KYC again to confirm your location and identity.",
  "delete_account": "DELETE ACCOUNT.",
  "confirm_that_you_would_like": "Confirm that you would like to\npermanently delete your account. This\nchange is irreversible. SwingStakes will\nretain your information for up to 30\ndays in accordance with our ",
  "and": " and ",
  "privacy_policys": "Privacy Policy",
  "confirm_deletion": "Confirm deletion",
  "swing_stakes": "SWING\nSTAKES",
  "match_compete_win": "MATCH. COMPETE. WIN.",
  "loading": "Loading..."
};
